export const paths = {
  root: "/",
  auth: {
    login: "/login",
    googleCallback: "/login/google",
  },
  integrations: {
    google: "/integrations/google",
    googleStatus: "/integrations/google/status",
  },
  tendering: {
    tenders: "/tendering/tenders",
    tenderCreate: "/tendering/tender/create",
    infoSheet: "/tendering/info-sheet",
    tenderApproval: "/tendering/tender-approval",
    phydocs: "/tendering/phydocs",
    rfqs: "/tendering/rfqs",
    emdsTenderFees: "/tendering/emds-tenderfees",
    checklists: "/tendering/checklists",
    costingSheets: "/tendering/costing-sheets",
    costingApproval: "/tendering/costing-approval",
    bidSubmissions: "/tendering/bid-submissions",
    tqs: "/tendering/tqs",
    ras: "/tendering/ras",
    results: "/tendering/results",
  },
  operations: {
    workOrder: "/operations/work-order",
    kickOff: "/operations/kick-off",
    contractAgreement: "/operations/contract-agreement",
  },
  services: {
    customer: "/services/customer",
    conference: "/services/conference",
    visit: "/services/visit",
    amc: "/services/amc",
  },
  bi: {
    demandDraft: "/bi-dashboard/demand-draft",
    fdr: "/bi-dashboard/fdr",
    cheque: "/bi-dashboard/cheque",
    bankGuarantee: "/bi-dashboard/bank-guarantee",
    bankTransfer: "/bi-dashboard/bank-tranfer",
    payOnPortal: "/bi-dashboard/pay-on-portal",
  },
  accounts: {
    imprests: "/accounts/imprests",
    financialDocs: "/accounts/financial-docs",
    loanAdvances: "/accounts/loan-advances",
    projects: "/accounts/projects",
    accountChecklists: "/accounts/task-checlkists",
    tdsChecklists: "/accounts/tds-checklists",
    gstChecklists: "/accounts/gst-checklists",
    fixedExpenses: "/accounts/fixed-expenses",
  },
  crm: {
    leads: "/crm/leads",
    enquiries: "/crm/enquiries",
    costings: "/crm/costings",
    quotations: "/crm/quotations",
  },
  performance: {
    tenderExecutive: "/performance/tender-executive",
    teamLeader: "/performance/team-leader",
    operationTeam: "/performance/operation-team",
    accountTeam: "/performance/account-team",
    oemDashboard: "/performance/oem-dashboard",
    businessDashboard: "/performance/business-dashboard",
    customerDashboard: "/performance/customer-dashboard",
    locationDashboard: "/performance/location-dashboard",
  },
  master: {
    users: "/master/users",
    users_create: "/master/users/create",
    users_edit: "/master/users/edit",
    statuses: "/master/statuses",
    statuses_create: "/master/statuses/create",
    statuses_edit: "/master/statuses/edit",
    organizations: "/master/organizations",
    organizations_create: "/master/organizations/create",
    organizations_edit: "/master/organizations/edit",
    companies: "/master/companies",
    items: "/master/items",
    items_create: "/master/items/create",
    items_edit: "/master/items/edit",
    vendors: "/master/vendors",
    vendors_create: "/master/vendors/create",
    vendors_edit: "/master/vendors/edit",
    websites: "/master/websites",
    websites_create: "/master/websites/create",
    websites_edit: "/master/websites/edit",
    locations: "/master/locations",
    locations_create: "/master/locations/create",
    locations_edit: "/master/locations/edit",
    documentSubmitted: "/master/document-submitted",
    documentSubmitted_create: "/master/document-submitted/create`",
    documentSubmitted_edit: "/master/document-submitted/edit",
    imprestCategory: "/master/imprest-category",
    imprestCategory_create: "/master/imprest-category/create",
    imprestCategory_edit: "/master/imprest-category/edit",
    documentType: "/master/document-type",
    documentType_create: "/master/document-type/create",
    documentType_edit: "/master/document-type/edit",
    financialYear: "/master/financial-year",
    financialYear_create: "/master/financial-year/create",
    financialYear_edit: "/master/financial-year/edit",
    followupCategories: "/master/followup-categories",
    followupCategories_create: "/master/followup-categories/create",
    followupCategories_edit: "/master/followup-categories/edit",
    emdsResponsibilities: "/master/emds-responsibilities",
    emdsResponsibilities_create: "/master/emds-responsibilities/create",
    emdsResponsibilities_edit: "/master/emds-responsibilities/edit",
  },
  shared: {
    followUps: "/shared/follow-ups",
    couriers: "/shared/courier",
  },
} as const;