CREATE TYPE "public"."deleteStatus" AS ENUM('1', '0');--> statement-breakpoint
CREATE TYPE "public"."tlStatus" AS ENUM('0', '1', '2', '3');--> statement-breakpoint
CREATE TABLE "tender_infos" (
	"id" serial PRIMARY KEY NOT NULL,
	"team" varchar(10) NOT NULL,
	"tender_no" varchar(255) NOT NULL,
	"organisation" varchar(255),
	"tender_name" varchar(255) NOT NULL,
	"item" varchar(255) NOT NULL,
	"gst_values" numeric(15, 2) NOT NULL,
	"tender_fees" numeric(15, 2) NOT NULL,
	"emd" numeric(15, 2) NOT NULL,
	"team_member" text NOT NULL,
	"due_date" date NOT NULL,
	"due_time" time NOT NULL,
	"remarks" varchar(200),
	"status" integer NOT NULL,
	"location" integer,
	"website" integer,
	"deleteStatus" "deleteStatus" DEFAULT '0' NOT NULL,
	"tlStatus" "tlStatus" DEFAULT '0' NOT NULL,
	"tlRemarks" varchar(200),
	"rfq_to" varchar(15),
	"courier_address" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tender_clients" (
	"id" serial PRIMARY KEY NOT NULL,
	"tender_id" bigint NOT NULL,
	"client_name" varchar(255),
	"designation" varchar(100),
	"mobile" varchar(20),
	"email" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "tender_documents" (
	"id" serial PRIMARY KEY NOT NULL,
	"tender_id" bigint NOT NULL,
	"doc_type" varchar(50),
	"doc_id" varchar(255),
	"doc_name" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "tender_information" (
	"id" serial PRIMARY KEY NOT NULL,
	"tender_id" bigint NOT NULL,
	"recommendation_by_te" varchar(5),
	"recommendation_reason" varchar(50),
	"recommendation_remarks" text,
	"processing_fees" numeric(15, 2),
	"processing_fees_form" varchar(50),
	"tender_fees" numeric(15, 2),
	"tender_fees_form" varchar(50),
	"emd" numeric(15, 2),
	"emd_required" varchar(15),
	"tender_value" numeric(15, 2),
	"emd_form" varchar(50),
	"bid_validity_days" integer,
	"commercial_evaluation" varchar(50),
	"ra_applicable" varchar(10),
	"maf_required" varchar(10),
	"delivery_time_supply" integer,
	"delivery_time_installation" integer,
	"delivery_inclusive_figure" varchar(100),
	"pbg_form" varchar(50),
	"pbg_percentage" numeric(6, 2),
	"pbg_duration_months" integer,
	"sd_form" varchar(50),
	"sd_percentage" numeric(6, 2),
	"sd_duration_months" integer,
	"ld_per_week_percentage" numeric(6, 2),
	"max_ld_percentage" numeric(6, 2),
	"physical_docs_required" varchar(10),
	"physical_docs_deadline" date,
	"eligibility_criterion" text,
	"eligibility_age_years" integer,
	"financial_criterion" text,
	"work_value_1" numeric(15, 2),
	"work_value_2" numeric(15, 2),
	"work_value_3" numeric(15, 2),
	"annual_avg_turnover" numeric(15, 2),
	"working_capital" numeric(15, 2),
	"net_worth" numeric(15, 2),
	"solvency_certificate" numeric(15, 2),
	"pqc_documents" text,
	"commercial_eligibility_documents" text,
	"documents_submitted" text,
	"client_organisation" varchar(255),
	"courier_address" text,
	"te_remark" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
