CREATE TABLE IF NOT EXISTS "sale_invoices" (
    "id" bigserial PRIMARY KEY,
    "project_id" bigint NOT NULL,
    "tender_id" bigint,
    "wo_detail_id" bigint,
    "invoice_number" varchar(255),
    "invoice_date" date,
    "billing_customer_name" varchar(255),
    "billing_address" text,
    "billing_gst" varchar(15),
    "shipping_customer_name" varchar(255),
    "shipping_address" text,
    "shipping_gst" varchar(15),
    "total_pre_gst" numeric(20,2),
    "total_gst" numeric(20,2),
    "grand_total" numeric(20,2),
    "invoice_taxable_amount" numeric(20,2),
    "invoice_igst" numeric(14,2),
    "invoice_cgst" numeric(14,2),
    "invoice_sgst" numeric(14,2),
    "invoice_total" numeric(20,2),
    "invoice_doc_paths" jsonb DEFAULT '[]',
    "cn_taxable" numeric(20,2),
    "cn_igst" numeric(14,2),
    "cn_cgst" numeric(14,2),
    "cn_sgst" numeric(14,2),
    "cn_total" numeric(20,2),
    "credit_note_doc_paths" jsonb DEFAULT '[]',
    "payment_advice_doc_paths" jsonb DEFAULT '[]',
    "payment_advice_requested_at" timestamptz,
    "payment_advice_received_at" timestamptz,
    "buyback_invoice_doc_paths" jsonb DEFAULT '[]',
    "gst_tds" numeric(14,2),
    "it_tds" numeric(14,2),
    "ld_deduction" numeric(14,2),
    "other_deduction" numeric(14,2),
    "net_received" numeric(20,2),
    "hold_gst_igst" numeric(14,2),
    "hold_gst_cgst" numeric(14,2),
    "hold_gst_sgst" numeric(14,2),
    "hold_itc" numeric(14,2),
    "hold_retention" numeric(14,2),
    "hold_buyback" numeric(14,2),
    "hold_other" numeric(14,2),
    "total_hold_amount" numeric(20,2),
    "hold_released_amount" numeric(20,2),
    "hold_released_at" timestamptz,
    "status" varchar(50) DEFAULT 'oe_request',
    "raised_by" bigint,
    "team" bigint,
    "remarks" text,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "sale_invoice_items" (
    "id" bigserial PRIMARY KEY,
    "sale_invoice_id" bigint NOT NULL REFERENCES "sale_invoices"("id") ON DELETE CASCADE,
    "sr_no" integer,
    "item_description" text,
    "quantity" numeric(20,2),
    "rate" numeric(20,2),
    "amount" numeric(20,2),
    "gst_rate" numeric(5,2),
    "gst_amount" numeric(14,2),
    "total_amount" numeric(14,2),
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now()
);
