import { z } from "zod";

export const createSaleInvoiceSchema = z.object({
    projectId: z.number(),
    woDetailId: z.number().optional(),
    invoiceDate: z.string().min(1, "Invoice date is required"),
    billingCustomerName: z.string().min(1, "Billing customer name is required"),
    billingAddress: z.string().min(1, "Billing address is required"),
    billingGst: z.string().optional().default(""),
    shippingCustomerName: z.string().min(1, "Shipping customer name is required"),
    shippingAddress: z.string().min(1, "Shipping address is required"),
    shippingGst: z.string().optional().default(""),
    dispatchFromName: z.string().optional().default(""),
    dispatchFromAddress: z.string().optional().default(""),
    dispatchFromGst: z.string().optional().default(""),
    dispatchVehicleNo: z.string().optional().default(""),
    dispatchLrNo: z.string().optional().default(""),
    dispatchToName: z.string().optional().default(""),
    dispatchToAddress: z.string().optional().default(""),
    dispatchToGst: z.string().optional().default(""),
    items: z.array(z.object({
        srNo: z.number().optional(),
        itemDescription: z.string().min(1, "Description is required"),
        qty: z.number(),
        rate: z.number(),
        gstRate: z.number().default(18),
        purchaseOrderProductId: z.number().optional(),
        unit: z.string().optional(),
        hsnSac: z.string().optional(),
    })).min(1, "At least one item is required"),
    remarks: z.string().optional().default(""),
});