export const paths = {
  root: "/",
  auth: {
    login: "/login",
  },
  tendering: {
    tenders: "/tendering/tenders",
    infoSheet: "/tendering/info-sheet",
    tenderApproval: "/tendering/tender-approval",
    phydocs: "/tendering/phydocs",
    rfqs: "/tendering/rfqs",
    emdsTenderFees: "/tendering/emds-tenderfees",
    checklists: "/tendering/checklists",
    costingSheets: "/tendering/costing-sheets",
    costingApproval: "/tendering/costing-approval",
    bidSubmissions: "/tendering/bid-submissions",
    tqs: "/tendering/tqs",
    ras: "/tendering/ras",
    results: "/tendering/results",
  },
  operations: {
    workOrder: "/operations/work-order",
    kickOff: "/operations/kick-off",
    contractAgreement: "/operations/contract-agreement",
  },
  services: {
    customer: "/services/customer",
    conference: "/services/conference",
    visit: "/services/visit",
    amc: "/services/amc",
  },
  bi: {
    demandDraft: "/bi-dashboard/demand-draft",
    fdr: "/bi-dashboard/fdr",
    cheque: "/bi-dashboard/cheque",
    bankGuarantee: "/bi-dashboard/bank-guarantee",
    bankTransfer: "/bi-dashboard/bank-tranfer",
    payOnPortal: "/bi-dashboard/pay-on-portal",
  },
  accounts: {
    imprests: "/accounts/imprests",
    financialDocs: "/accounts/financial-docs",
    loanAdvances: "/accounts/loan-advances",
    projects: "/accounts/projects",
    accountChecklists: "/accounts/task-checlkists",
    tdsChecklists: "/accounts/tds-checklists",
    gstChecklists: "/accounts/gst-checklists",
    fixedExpenses: "/accounts/fixed-expenses",
  },
  crm: {
    leads: "/crm/leads",
    enquiries: "/crm/enquiries",
    costings: "/crm/costings",
    quotations: "/crm/quotations",
  },
  performance: {
    tenderExecutive: "/performance/tender-executive",
    teamLeader: "/performance/team-leader",
    operationTeam: "/performance/operation-team",
    accountTeam: "/performance/account-team",
    oemDashboard: "/performance/oem-dashboard",
    businessDashboard: "/performance/business-dashboard",
    customerDashboard: "/performance/customer-dashboard",
    locationDashboard: "/performance/location-dashboard",
  },
  master: {
    employees: "/master/employees",
    statuses: "/master/statuses",
    organizations: "/master/organizations",
    items: "/master/items",
    vendors: "/master/vendors",
    websites: "/master/websites",
    locations: "/master/locations",
    documentSubmitted: "/master/document-submitted",
    imprestCategory: "/master/imprest-category",
    documentType: "/master/document-type",
    financialYear: "/master/financial-year",
    followupCategories: "/master/followup-categories",
    emdsResponsibilities: "/master/emds-responsibilities",
  },
  shared: {
    followUps: "/shared/follow-ups",
    couriers: "/shared/courier",
  },
} as const;
