export const tlDecisionOptions = [
    { value: '1', label: 'Yes - Proceed with Bidding' },
    { value: '2', label: 'No - Do Not Bid' },
    { value: '3', label: 'Info Sheet Incomplete' },
];

export const documentApprovalOptions = [
    { value: '1', label: 'Approve' },
    { value: '2', label: 'Reject' },
];

export const infoSheetFieldOptions = [
    { value: 'teRecommendation', label: 'TE Recommendation' },
    { value: 'teRejectionReason', label: 'TE Rejection Reason' },
    { value: 'processingFeeAmount', label: 'Processing Fee Amount' },
    { value: 'processingFeeMode', label: 'Processing Fee Mode' },
    { value: 'tenderFeeAmount', label: 'Tender Fee Amount' },
    { value: 'tenderFeeMode', label: 'Tender Fee Mode' },
    { value: 'emdRequired', label: 'EMD Required' },
    { value: 'emdMode', label: 'EMD Mode' },
    { value: 'reverseAuctionApplicable', label: 'Reverse Auction Applicable' },
    { value: 'paymentTermsSupply', label: 'Payment Terms (Supply)' },
    { value: 'paymentTermsInstallation', label: 'Payment Terms (Installation)' },
    { value: 'bidValidityDays', label: 'Bid Validity Days' },
    { value: 'commercialEvaluation', label: 'Commercial Evaluation' },
    { value: 'mafRequired', label: 'MAF Required' },
    { value: 'deliveryTimeSupply', label: 'Delivery Time (Supply)' },
    { value: 'deliveryTimeInstallation', label: 'Delivery Time (Installation)' },
    { value: 'pbgInFormOf', label: 'PBG In Form Of' },
    { value: 'pbgPercentage', label: 'PBG Percentage' },
    { value: 'pbgDurationMonths', label: 'PBG Duration (Months)' },
    { value: 'sdInFormOf', label: 'Security Deposit In Form Of' },
    { value: 'securityDepositPercentage', label: 'Security Deposit Percentage' },
    { value: 'sdDurationMonths', label: 'SD Duration (Months)' },
    { value: 'ldPercentagePerWeek', label: 'LD Percentage Per Week' },
    { value: 'maxLdPercentage', label: 'Max LD Percentage' },
    { value: 'physicalDocsRequired', label: 'Physical Documents Required' },
    { value: 'physicalDocsDeadline', label: 'Physical Documents Deadline' },
    { value: 'techEligibilityAgeYears', label: 'Technical Eligibility Age (Years)' },
    { value: 'orderValues', label: 'Order Values' },
    { value: 'avgAnnualTurnover', label: 'Average Annual Turnover' },
    { value: 'workingCapital', label: 'Working Capital' },
    { value: 'solvencyCertificate', label: 'Solvency Certificate' },
    { value: 'netWorth', label: 'Net Worth' },
    { value: 'clientOrganisation', label: 'Client Organisation' },
    { value: 'clientContacts', label: 'Client Contacts' },
    { value: 'courierAddress', label: 'Courier Address' },
    { value: 'technicalDocuments', label: 'Technical Documents' },
    { value: 'financialDocuments', label: 'Financial Documents' },
];
