export interface EmployeeAsset {
    id: number;
    userId: number;
    assetCode: string;
    assetType: string;
    assetTypeLabel?: string;
    assetCategory?: string;
    assetCategoryLabel?: string;
    brand?: string;
    model?: string;
    specifications?: string;
    serialNumber?: string;
    imeiNumber?: string;
    licenseKey?: string;
    assetValue?: string;
    assetCondition?: string;
    assetConditionLabel?: string;
    assignedDate: string;
    assignedBy?: number;
    expectedReturnDate?: string;
    purpose?: string;
    assetLocation?: string;
    assetLocationLabel?: string;
    warrantyFrom?: string;
    warrantyTo?: string;
    insuranceDetails?: string;
    accessories?: string[];
    assetPhotos?: string[];
    purchaseInvoiceUrl?: string;
    warrantyCardUrl?: string;
    assignmentFormUrl?: string;
    assetStatus?: string;
    assetStatusLabel?: string;
    returnDate?: string;
    returnCondition?: string;
    damageRemarks?: string;
    deductionAmount?: string;
    purchaseDate?: string;
    purchasePrice?: string;
    purchaseFrom?: string;
    remarks?: string;
    createdAt?: string;
    updatedAt?: string;
    [key: string]: any;
}

export interface StatusUpdatePayload {
    assetStatus: string;
    userId?: number;
    assignedDate?: string;
    expectedReturnDate?: string;
    purpose?: string;
    assetLocation?: string;
    returnDate?: string;
    returnCondition?: string;
    assetCondition?: string;
    damageDate?: string;
    damageType?: string;
    damageDescription?: string;
    isRepairable?: string;
    lostDate?: string;
    lostLocation?: string;
    lostCircumstances?: string;
    policeReportNumber?: string;
    policeReportDate?: string;
    repairStartDate?: string;
    repairEndDate?: string;
    repairEstimatedCost?: string;
    repairActualCost?: string;
    repairVendor?: string;
    repairDescription?: string;
    deductionAmount?: string;
    deductionReason?: string;
    remarks?: string;
}

export interface AssetHistoryEntry {
    id: number;
    assetId: number;
    previousStatus?: string | null;
    previousStatusLabel?: string | null;
    newStatus: string;
    newStatusLabel?: string;
    actionType: string;
    assignedToUserId?: number | null;
    assignedByUserId?: number | null;
    assignedDate?: string | null;
    expectedReturnDate?: string | null;
    purpose?: string | null;
    assetLocation?: string | null;
    assetLocationLabel?: string | null;
    returnDate?: string | null;
    returnCondition?: string | null;
    returnConditionLabel?: string | null;
    damageDate?: string | null;
    damageType?: string | null;
    damageDescription?: string | null;
    isRepairable?: string | null;
    lostDate?: string | null;
    lostLocation?: string | null;
    lostCircumstances?: string | null;
    policeReportNumber?: string | null;
    policeReportDate?: string | null;
    repairStartDate?: string | null;
    repairEndDate?: string | null;
    repairEstimatedCost?: string | null;
    repairActualCost?: string | null;
    repairVendor?: string | null;
    repairDescription?: string | null;
    deductionAmount?: string | null;
    deductionReason?: string | null;
    assetConditionAfter?: string | null;
    assetConditionAfterLabel?: string | null;
    remarks?: string | null;
    changedByUserId?: number | null;
    createdAt: string;
}

export const MOBILE_TYPES = ["3", "11"];
