import type {
  UserData,
  ProfileData,
  EmployeeProfileData,
  AddressData,
  EmergencyContactData,
  DocumentData,
  AssetData,
  NotificationData,
  ComplaintData,
} from "./types";

export const CURRENT_USER: UserData = {
  id: 1,
  name: "Arjun Mehta",
  username: "arjun.mehta",
  email: "arjun.mehta@company.com",
  mobile: "+91 98765 43210",
  isActive: true,
  lastLoginAt: "2025-01-15T10:30:00Z",
  createdAt: "2023-06-15T00:00:00Z",
  team: "Engineering",
};

export const PROFILE: ProfileData = {
  firstName: "Arjun",
  middleName: "Kumar",
  lastName: "Mehta",
  dateOfBirth: "1995-03-22",
  gender: "Male",
  maritalStatus: "Single",
  nationality: "Indian",
  personalEmail: "arjun.personal@gmail.com",
  phone: "+91 98765 43210",
  alternatePhone: "+91 87654 32109",
  aadharNumber: "XXXX XXXX 4589",
  panNumber: "ABCDE1234F",
  employeeCode: "EMP24X9K2",
  altEmail: "arjun.alt@gmail.com",
};

export const EMPLOYEE_PROFILE: EmployeeProfileData = {
  employeeType: "Full Time",
  employeeStatus: "Active",
  workLocation: "Bengaluru, Karnataka",
  officialEmail: "arjun.mehta@company.com",
  reportingManager: "Priya Sharma",
  probationMonths: 6,
  probationEndDate: "2023-12-15",
  salaryType: "Monthly",
  bankName: "HDFC Bank",
  accountHolderName: "Arjun Kumar Mehta",
  accountNumber: "XXXX XXXX 7821",
  ifscCode: "HDFC0001234",
  branchName: "Koramangala, Bengaluru",
  uanNumber: "1001 2345 6789",
  pfNumber: "KA/BLR/0012345/000/0001234",
  esicNumber: "31-00-123456-000-0001",
  offerLetterDate: "2023-05-20",
  joiningLetterIssued: true,
  inductionCompleted: true,
  inductionDate: "2023-06-20",
  idCardIssued: true,
  idCardIssuedDate: "2023-06-25",
  joiningDate: "2023-06-15",
  designation: "Senior Software Engineer",
  department: "Engineering",
};

export const ADDRESS: AddressData = {
  currentAddressLine1: "42, 3rd Cross, HSR Layout",
  currentAddressLine2: "Sector 7, Near Agara Lake",
  currentCity: "Bengaluru",
  currentState: "Karnataka",
  currentCountry: "India",
  currentPostalCode: "560102",
  permanentAddressLine1: "15, MG Road, Sector 4",
  permanentAddressLine2: "Near Central Park",
  permanentCity: "Jaipur",
  permanentState: "Rajasthan",
  permanentCountry: "India",
  permanentPostalCode: "302001",
};

export const EMERGENCY_CONTACT: EmergencyContactData = {
  name: "Sunita Mehta",
  relationship: "Mother",
  phone: "+91 99887 76655",
  altPhone: "+91 88776 65544",
  email: "sunita.mehta@gmail.com",
};

export const DOCUMENTS: DocumentData[] = [
  {
    id: 1,
    docCategory: "Identity",
    docType: "Aadhar Card",
    docNumber: "XXXX XXXX 4589",
    fileUrl: "/docs/aadhar.pdf",
    issueDate: "2018-01-15",
    expiryDate: null,
    verificationStatus: "verified",
    remarks: null,
  },
  {
    id: 2,
    docCategory: "Identity",
    docType: "PAN Card",
    docNumber: "ABCDE1234F",
    fileUrl: "/docs/pan.pdf",
    issueDate: "2017-06-10",
    expiryDate: null,
    verificationStatus: "verified",
    remarks: null,
  },
  {
    id: 3,
    docCategory: "Education",
    docType: "B.Tech Degree",
    docNumber: null,
    fileUrl: "/docs/degree.pdf",
    issueDate: "2017-07-01",
    expiryDate: null,
    verificationStatus: "verified",
    remarks: null,
  },
  {
    id: 4,
    docCategory: "Employment",
    docType: "Previous Experience Letter",
    docNumber: null,
    fileUrl: "/docs/experience.pdf",
    issueDate: "2023-05-30",
    expiryDate: null,
    verificationStatus: "pending",
    remarks: "Under review by HR",
  },
  {
    id: 5,
    docCategory: "Employment",
    docType: "Offer Letter",
    docNumber: "OL-2023-0456",
    fileUrl: "/docs/offer.pdf",
    issueDate: "2023-05-20",
    expiryDate: null,
    verificationStatus: "verified",
    remarks: null,
  },
  {
    id: 6,
    docCategory: "Financial",
    docType: "Bank Statement",
    docNumber: null,
    fileUrl: "/docs/bank.pdf",
    issueDate: "2024-12-01",
    expiryDate: null,
    verificationStatus: "rejected",
    remarks: "Document is blurry. Please re-upload a clear copy.",
  },
];

export const ASSETS: AssetData[] = [
  {
    id: 1,
    assetCode: "AST-2023-L001",
    assetType: "Laptop",
    brand: "Apple",
    model: 'MacBook Pro 14"',
    serialNumber: "C02X1234HASH",
    assetCondition: "Good",
    assignedDate: "2023-06-15",
    assetStatus: "Assigned",
  },
  {
    id: 2,
    assetCode: "AST-2023-M001",
    assetType: "Monitor",
    brand: "Dell",
    model: "UltraSharp U2723QE",
    serialNumber: "DL-MON-89012",
    assetCondition: "Good",
    assignedDate: "2023-06-15",
    assetStatus: "Assigned",
  },
  {
    id: 3,
    assetCode: "AST-2023-K001",
    assetType: "Keyboard",
    brand: "Logitech",
    model: "MX Keys Mini",
    serialNumber: "LG-KEY-34567",
    assetCondition: "Good",
    assignedDate: "2023-06-16",
    assetStatus: "Assigned",
  },
];

export const NOTIFICATIONS: NotificationData[] = [
  {
    id: 1,
    title: "Document Verified",
    message: "Your B.Tech Degree has been verified by HR.",
    time: "2 hours ago",
    read: false,
    type: "success",
  },
  {
    id: 2,
    title: "Document Rejected",
    message:
      "Your Bank Statement was rejected. Please re-upload a clear copy.",
    time: "1 day ago",
    read: false,
    type: "error",
  },
  {
    id: 3,
    title: "Training Assigned",
    message:
      'New training "Code Review Best Practices" has been assigned to you.',
    time: "2 days ago",
    read: true,
    type: "info",
  },
  {
    id: 4,
    title: "Policy Update",
    message: "Updated WFH policy has been published. Please review.",
    time: "3 days ago",
    read: true,
    type: "info",
  },
  {
    id: 5,
    title: "Asset Acknowledgment",
    message: 'Please acknowledge receipt of "Dell UltraSharp Monitor".',
    time: "5 days ago",
    read: true,
    type: "warning",
  },
];

export const COMPLAINTS: ComplaintData[] = [
  {
    id: 1,
    complaintCode: "CMP-2024-001",
    subject: "AC not working in conference room B",
    status: "resolved",
    priority: "medium",
    createdAt: "2024-11-10",
  },
  {
    id: 2,
    complaintCode: "CMP-2025-002",
    subject: "Internet connectivity issues on 3rd floor",
    status: "in_progress",
    priority: "high",
    createdAt: "2025-01-08",
  },
];
