// INSTRUMENT STATUS CONFIGURATION
// Status prefix dropped (instrument type already in DB field)

export type InstrumentType = 'DD' | 'FDR' | 'BG' | 'Cheque' | 'Bank Transfer' | 'Portal Payment';

// COMMON STATUSES - Shared across all instrument types

export const COMMON_STATUSES = {
  PENDING: 'PENDING',
  ACCOUNTS_FORM_ACCEPTED: 'ACCOUNTS_FORM_ACCEPTED',
  ACCOUNTS_FORM_REJECTED: 'ACCOUNTS_FORM_REJECTED',
  FOLLOWUP_INITIATED: 'FOLLOWUP_INITIATED',
  RETURN_VIA_COURIER: 'RETURN_VIA_COURIER',
  RETURN_VIA_BANK_TRANSFER: 'RETURN_VIA_BANK_TRANSFER',
  SETTLED_WITH_PROJECT: 'SETTLED_WITH_PROJECT',
  CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
  CANCELLED: 'CANCELLED',
} as const;

// INSTRUMENT-SPECIFIC STATUSES - Only for instruments with unique statuses

export const BG_SPECIFIC_STATUSES = {
  BG_CREATED: 'BG_CREATED',
  FDR_DETAILS_CAPTURED: 'FDR_DETAILS_CAPTURED',
  EXTENSION_REQUESTED: 'EXTENSION_REQUESTED',
  BG_CANCELLATION_CONFIRMED: 'BG_CANCELLATION_CONFIRMED',
  FDR_CANCELLED_CONFIRMED: 'FDR_CANCELLED_CONFIRMED',
} as const;

export const CHEQUE_SPECIFIC_STATUSES = {
  STOP_REQUESTED: 'STOP_REQUESTED',
  DEPOSITED_IN_BANK: 'DEPOSITED_IN_BANK',
  PAID_VIA_BANK_TRANSFER: 'PAID_VIA_BANK_TRANSFER',
  CANCELLED_TORN: 'CANCELLED_TORN',
} as const;

// STATUSES EXPORTS - Only what's actually used

export const DD_STATUSES = { ...COMMON_STATUSES };
export const FDR_STATUSES = { ...COMMON_STATUSES };
export const BG_STATUSES = { ...COMMON_STATUSES, ...BG_SPECIFIC_STATUSES };
export const CHEQUE_STATUSES = { ...COMMON_STATUSES, ...CHEQUE_SPECIFIC_STATUSES };
export const BT_STATUSES = { ...COMMON_STATUSES };
export const PORTAL_STATUSES = { ...COMMON_STATUSES };