// ============================================================================
// INSTRUMENT STATUS CONFIGURATION
// Status prefix dropped (instrument type already in DB field)
// ============================================================================

export type InstrumentType = 'DD' | 'FDR' | 'BG' | 'Cheque' | 'Bank Transfer' | 'Portal Payment';

// ============================================================================
// COMMON STATUSES - Shared across all instrument types
// ============================================================================

export const COMMON_STATUSES = {
  PENDING: 'PENDING',
  ACCOUNTS_FORM_ACCEPTED: 'ACCOUNTS_FORM_ACCEPTED',
  ACCOUNTS_FORM_REJECTED: 'ACCOUNTS_FORM_REJECTED',
  FOLLOWUP_INITIATED: 'FOLLOWUP_INITIATED',
  RETURN_VIA_COURIER: 'RETURN_VIA_COURIER',
  RETURN_VIA_BANK_TRANSFER: 'RETURN_VIA_BANK_TRANSFER',
  SETTLED_WITH_PROJECT: 'SETTLED_WITH_PROJECT',
  CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
  CANCELLED: 'CANCELLED',
} as const;

// ============================================================================
// INSTRUMENT-SPECIFIC STATUSES - Only for instruments with unique statuses
// ============================================================================

export const BG_SPECIFIC_STATUSES = {
  BG_CREATED: 'BG_CREATED',
  FDR_DETAILS_CAPTURED: 'FDR_DETAILS_CAPTURED',
  EXTENSION_REQUESTED: 'EXTENSION_REQUESTED',
  BG_CANCELLATION_CONFIRMED: 'BG_CANCELLATION_CONFIRMED',
  FDR_CANCELLED_CONFIRMED: 'FDR_CANCELLED_CONFIRMED',
} as const;

export const CHEQUE_SPECIFIC_STATUSES = {
  STOP_REQUESTED: 'STOP_REQUESTED',
  DEPOSITED_IN_BANK: 'DEPOSITED_IN_BANK',
  PAID_VIA_BANK_TRANSFER: 'PAID_VIA_BANK_TRANSFER',
  CANCELLED_TORN: 'CANCELLED_TORN',
} as const;

// ============================================================================
// STATUSES EXPORTS - Only what's actually used
// ============================================================================

export const DD_STATUSES = { ...COMMON_STATUSES };
export const FDR_STATUSES = { ...COMMON_STATUSES };
export const BG_STATUSES = { ...COMMON_STATUSES, ...BG_SPECIFIC_STATUSES };
export const CHEQUE_STATUSES = { ...COMMON_STATUSES, ...CHEQUE_SPECIFIC_STATUSES };
export const BT_STATUSES = { ...COMMON_STATUSES };
export const PORTAL_STATUSES = { ...COMMON_STATUSES };

// ============================================================================
// DB MIGRATION MAP (Optional - for updating old DB values)
// ============================================================================

export const STATUS_MIGRATION_MAP: Record<string, string> = {
  // DD
  'DD_ACCOUNTS_FORM_PENDING': COMMON_STATUSES.PENDING,
  'DD_ACCOUNTS_FORM_ACCEPTED': COMMON_STATUSES.ACCOUNTS_FORM_ACCEPTED,
  'DD_ACCOUNTS_FORM_REJECTED': COMMON_STATUSES.ACCOUNTS_FORM_REJECTED,
  'DD_FOLLOWUP_INITIATED': COMMON_STATUSES.FOLLOWUP_INITIATED,
  'DD_RETURN_VIA_COURIER': COMMON_STATUSES.RETURN_VIA_COURIER,
  'DD_RETURN_VIA_BANK_TRANSFER': COMMON_STATUSES.RETURN_VIA_BANK_TRANSFER,
  'DD_SETTLED_WITH_PROJECT': COMMON_STATUSES.SETTLED_WITH_PROJECT,
  'DD_CANCELLATION_REQUESTED': COMMON_STATUSES.CANCELLATION_REQUESTED,
  'DD_CANCELLED_AT_BRANCH': COMMON_STATUSES.CANCELLED,
  // FDR
  'FDR_ACCOUNTS_FORM_PENDING': COMMON_STATUSES.PENDING,
  'FDR_ACCOUNTS_FORM_ACCEPTED': COMMON_STATUSES.ACCOUNTS_FORM_ACCEPTED,
  'FDR_ACCOUNTS_FORM_REJECTED': COMMON_STATUSES.ACCOUNTS_FORM_REJECTED,
  'FDR_FOLLOWUP_INITIATED': COMMON_STATUSES.FOLLOWUP_INITIATED,
  'FDR_RETURN_VIA_COURIER': COMMON_STATUSES.RETURN_VIA_COURIER,
  'FDR_RETURN_VIA_BANK_TRANSFER': COMMON_STATUSES.RETURN_VIA_BANK_TRANSFER,
  'FDR_SETTLED_WITH_PROJECT': COMMON_STATUSES.SETTLED_WITH_PROJECT,
  'FDR_CANCELLATION_REQUESTED': COMMON_STATUSES.CANCELLATION_REQUESTED,
  'FDR_CANCELLED_AT_BRANCH': COMMON_STATUSES.CANCELLED,
  // BG
  'BG_ACCOUNTS_FORM_PENDING': COMMON_STATUSES.PENDING,
  'BG_ACCOUNTS_FORM_ACCEPTED': COMMON_STATUSES.ACCOUNTS_FORM_ACCEPTED,
  'BG_ACCOUNTS_FORM_REJECTED': COMMON_STATUSES.ACCOUNTS_FORM_REJECTED,
  'BG_CREATED': BG_SPECIFIC_STATUSES.BG_CREATED,
  'BG_FDR_DETAILS_CAPTURED': BG_SPECIFIC_STATUSES.FDR_DETAILS_CAPTURED,
  'BG_FOLLOWUP_INITIATED': COMMON_STATUSES.FOLLOWUP_INITIATED,
  'BG_EXTENSION_REQUESTED': BG_SPECIFIC_STATUSES.EXTENSION_REQUESTED,
  'BG_RETURN_VIA_COURIER': COMMON_STATUSES.RETURN_VIA_COURIER,
  'BG_CANCELLATION_REQUESTED': COMMON_STATUSES.CANCELLATION_REQUESTED,
  'BG_BG_CANCELLATION_CONFIRMED': BG_SPECIFIC_STATUSES.BG_CANCELLATION_CONFIRMED,
  'BG_FDR_CANCELLED_CONFIRMED': BG_SPECIFIC_STATUSES.FDR_CANCELLED_CONFIRMED,
  // Cheque
  'CHEQUE_ACCOUNTS_FORM_PENDING': COMMON_STATUSES.PENDING,
  'CHEQUE_ACCOUNTS_FORM_ACCEPTED': COMMON_STATUSES.ACCOUNTS_FORM_ACCEPTED,
  'CHEQUE_ACCOUNTS_FORM_REJECTED': COMMON_STATUSES.ACCOUNTS_FORM_REJECTED,
  'CHEQUE_FOLLOWUP_INITIATED': COMMON_STATUSES.FOLLOWUP_INITIATED,
  'CHEQUE_STOP_FROM_BANK': CHEQUE_SPECIFIC_STATUSES.STOP_REQUESTED,
  'CHEQUE_DEPOSITED_IN_BANK': CHEQUE_SPECIFIC_STATUSES.DEPOSITED_IN_BANK,
  'CHEQUE_PAID_VIA_BANK_TRANSFER': CHEQUE_SPECIFIC_STATUSES.PAID_VIA_BANK_TRANSFER,
  'CHEQUE_CANCELLED_TORN': CHEQUE_SPECIFIC_STATUSES.CANCELLED_TORN,
  // Bank Transfer
  'Bank Transfer_ACCOUNTS_FORM_PENDING': COMMON_STATUSES.PENDING,
  'Bank Transfer_ACCOUNTS_FORM_ACCEPTED': COMMON_STATUSES.ACCOUNTS_FORM_ACCEPTED,
  'Bank Transfer_ACCOUNTS_FORM_REJECTED': COMMON_STATUSES.ACCOUNTS_FORM_REJECTED,
  'Bank Transfer_FOLLOWUP_INITIATED': COMMON_STATUSES.FOLLOWUP_INITIATED,
  'Bank Transfer_RETURN_VIA_BANK_TRANSFER': COMMON_STATUSES.RETURN_VIA_BANK_TRANSFER,
  'Bank Transfer_SETTLED_WITH_PROJECT': COMMON_STATUSES.SETTLED_WITH_PROJECT,
  // Portal Payment
  'Portal Payment_ACCOUNTS_FORM_PENDING': COMMON_STATUSES.PENDING,
  'Portal Payment_ACCOUNTS_FORM_ACCEPTED': COMMON_STATUSES.ACCOUNTS_FORM_ACCEPTED,
  'Portal Payment_ACCOUNTS_FORM_REJECTED': COMMON_STATUSES.ACCOUNTS_FORM_REJECTED,
  'Portal Payment_FOLLOWUP_INITIATED': COMMON_STATUSES.FOLLOWUP_INITIATED,
  'Portal Payment_RETURN_VIA_BANK_TRANSFER': COMMON_STATUSES.RETURN_VIA_BANK_TRANSFER,
  'Portal Payment_SETTLED_WITH_PROJECT': COMMON_STATUSES.SETTLED_WITH_PROJECT,
};