export const PAYMENT_AGAINST_LABELS: Record<string, string> = {
    upload_invoice: "Upload Invoice",
    new_pi: "New PI",
    po: "PO",
    vwo: "Work Order (V)",
    others: "Imprest",
    imprest: "Imprest",
    fixed: 'Fixed',
    loan_return: 'Loan Repayment/Return',
    own_bank: 'Own Bank',
    capital_asset_purchase: 'Capital/Asset Purchase',
    communication: 'Communication',
    courier: 'Courier',
    electricity: 'Electricity',
    rent: 'Rent',
    emi: 'EMI',
    salary: 'Salary',
    software: 'Software',
    office_expenses: 'Office Expenses',
    od_ac_interest: 'OD A/C Interest',
    printing_stationary: 'Printing & Stationary',
    office_maintenance: 'Office Maintenance',
    related_party: 'Related Party',
    nbfc_oc_acc: 'NBFC OC Account',
    loan_principal_return: 'Loan Principal Return',
    AU_5242: 'AU Current Account (AU_5242)',
    AU_5180: 'AU Inflow Account (AU_5180)',
    AU_5190: 'AU Expenses Account (AU_5190)',
    AU_8316: 'AU Outflow Account (AU_8316)',
    AU_9589: 'AU EMD Account (AU_9589)',
    AU_9284: 'AU Cash Reserve Account (AU_9284)',
    amex_cc: 'Amex Company Credit Card',
    investment: 'Investment',
    asset_purchase: 'Asset Purchase',
    portal_renewal_charges: 'Portal Renewal Charges',
    professional_charges: 'Professional Charges',
    insurance: 'Insurance',
    YES_BANK_2011: 'Yes Bank Inflow Account (2011)',
    YES_BANK_0771: "Yes Bank (0771)",
    gem_charges: 'GeM Charges'
};

export const STATUS_CONFIG: Record<string, { label: string; color: string }> = {
    pending: { label: "Pending", color: "text-yellow-600 bg-yellow-50" },
    maker_done: { label: "Maker Done", color: "text-blue-600 bg-blue-50" },
    payment_done: { label: "Payment Done", color: "text-green-600 bg-green-50" },
    rejected: { label: "Rejected", color: "text-red-600 bg-red-50" },
};
